- name: Install Rust
  command:
    cmd: "{{ item }}"
    warn: false
    creates: "{{ homedir }}/.rustup"
  become: true
  become_user: "{{ user }}"
  with_items:
  - "wget -O /tmp/rustup.sh https://sh.rustup.rs"
  - "chmod +x /tmp/rustup.sh"
  - "/tmp/rustup.sh -y"
  - "rm /tmp/rustup.sh"

- name: Set path for Rust
  set_fact:
    pathvar: "{{ pathvar|default({}) | combine({ 'Rust': ['PATH=$PATH:$HOME/.cargo/bin'] }) }}"
