- hosts: [jeff-ubuntu2204]
  remote_user: jeff
  become: true
  # connection: local
  roles:
    - begin
    - packages
    # - vmware
    - shell
    - fonts
    - ohmyzsh
    - desktop
    - rust
    - shell_enhancements
    - gitconfig
    - end
