- name: Install basic packages
  package:
    name: '{{ os_defaults[ansible_distribution].packages.packages }}'
    state: present

- name: Install Python packages
  pip:
    name: '{{ os_defaults[ansible_distribution].packages.pip_packages }}'
    state: present
    executable: pip3
