- name: Enable fingerprint sudo
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sudo
    insertbefore: '^auth       sufficient     pam_smartcard.so'
    line: 'auth       sufficient     pam_tid.so'
  become: true
  when: fingerprint == true
