- name: DISPLAY environment variable
  copy:
    src: files/display
    dest: /home/jeff/.extra_env/display
    owner: '{{ user }}'
    group: '{{ group }}'

- name: Start VPNKit
  copy:
    src: files/vpnkit
    dest: /home/jeff/.extra_rc/vpnkit
    owner: '{{ user }}'
    group: '{{ group }}'
