- name: Git package
  package:
    name: git
    state: present

- name: .gitignore
  copy:
    src: files/gitignore
    dest: "{{ homedir }}/.gitignore"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: .gitconfig
  template:
    src: gitconfig.j2
    dest: "{{ homedir }}/.gitconfig"
    owner: "{{ user }}"
    group: "{{ group }}"

# ------------------------------------------------------------------------------
# $HOME/.git-functions
# ------------------------------------------------------------------------------
- name: git-functions directory
  file:
    name: "{{ homedir }}/.git-functions"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: git-functions files
  synchronize:
    src: files/git-functions/
    dest: "{{ homedir }}/.git-functions/"
    recursive: yes
    rsync_opts:
    - "--chown={{ user }}:{{ group }}"

# ------------------------------------------------------------------------------
# $HOME/.git-templates
# ------------------------------------------------------------------------------
- name: git-templates directory
  file:
    name: "{{ homedir }}/.git-templates"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: git-templates files
  synchronize:
    src: files/git-templates/
    dest: "{{ homedir }}/.git-templates/"
    recursive: yes
    rsync_opts:
    - "--chown={{ user }}:{{ group }}"
