- name: Cargo Packages
  ansible.builtin.command:
    cmd: '{{ homedir }}/.cargo/bin/cargo install {{ item.name }}'
    chdir: '{{ homedir }}'
    creates: '{{ homedir }}/.cargo/bin/{{ item.file }}'
  become_user: '{{ user }}'
  with_items:
  - { name: bat,       file: bat }
  - { name: exa,       file: exa }
  - { name: broot,     file: broot }
  - { name: fd-find,   file: fd }
  - { name: git-delta, file: delta }
  - { name: ripgrep,   file: rg }
  - { name: sd,        file: sd }

- name: Alias .extra_aliases/exa
  copy:
    src: files/aliases/exa
    dest: '{{ homedir }}/.extra_aliases/exa'
    owner: '{{ user }}'
    group: '{{ group }}'
