- name: Cargo Packages
  ansible.builtin.command:
    cmd: "{{ homedir }}/.cargo/bin/cargo install {{ item }}"
    chdir: "{{ homedir }}"
    warn: false
  become_user: "{{ user }}"
  with_items:
  - bat
  - exa
  - broot
  - fd-find
  - git-delta
  - ripgrep
  - sd

- name: Alias .extra_aliases/exa
  copy:
    src: files/aliases/exa
    dest: "{{ homedir }}/.extra_aliases/exa"
    owner: "{{ user }}"
    group: "{{ group }}"
